[phases.setup]
nixPkgs = ["python311", "gcc", "nodejs_20"]

[phases.install]
cmds = [
  "cd .. && npm install",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd .. && npm run build"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
